Flex Bison C++ Example: CNAdd Class Reference
CNAdd Class Reference
Calculation node adding two operand nodes.
#include <expression.h>
Public Member Functions
CNAdd (CalcNode *_left, CalcNode *_right)
virtual ~CNAdd ()
virtual double evaluate () const
evaluate the complete calculation tree and return the floating point result value
virtual void print (std::ostream &os, unsigned int depth) const
output the calculation tree to the given stream.
Private Attributes
CalcNode * left
left calculation operand
CalcNode * right
right calculation operand
Detailed Description
Calculation node adding two operand nodes.
Definition at line 93 of file expression.h.
Constructor & Destructor Documentation
CNAdd::CNAdd (CalcNode * _left, CalcNode * _right) [inline, explicit]
Definition at line 102 of file expression.h.
virtual CNAdd::~CNAdd () [inline, virtual]
Definition at line 107 of file expression.h.
References left, and right.
Member Function Documentation
virtual double CNAdd::evaluate () const [inline, virtual]
evaluate the complete calculation tree and return the floating point result value
Implements CalcNode.
Definition at line 113 of file expression.h.
References CalcNode::evaluate(), left, and right.
virtual void CNAdd::print (std::ostream & os, unsigned int depth) const [inline, virtual]
output the calculation tree to the given stream.
tries to format the output to make tree levels visible.
Implements CalcNode.
Definition at line 118 of file expression.h.
References CalcNode::indent(), left, CalcNode::print(), and right.
Member Data Documentation
CalcNode* CNAdd::left [private]
left calculation operand
Definition at line 96 of file expression.h.
Referenced by evaluate(), print(), and ~CNAdd().
CalcNode* CNAdd::right [private]
right calculation operand
Definition at line 99 of file expression.h.
Referenced by evaluate(), print(), and ~CNAdd().
The documentation for this class was generated from the following file:
src/expression.h