Flex Bison C++ Example: ExampleFlexLexer Class Reference
ExampleFlexLexer Class Reference
#include <FlexLexer.h>
Public Member Functions
ExampleFlexLexer (std::istream *arg_yyin=0, std::ostream *arg_yyout=0)
virtual ~ExampleFlexLexer ()
void yy_switch_to_buffer (struct yy_buffer_state *new_buffer)
struct yy_buffer_state * yy_create_buffer (std::istream *s, int size)
Allocate and initialize an input buffer state.
void yy_delete_buffer (struct yy_buffer_state *b)
void yyrestart (std::istream *s)
Immediately switch to a different input stream.
void yypush_buffer_state (struct yy_buffer_state *new_buffer)
void yypop_buffer_state ()
Removes and deletes the top of the stack, if present.
virtual int yylex ()
The main scanner function which does all the work.
virtual void switch_streams (std::istream *new_in, std::ostream *new_out)
virtual int yywrap ()
Protected Member Functions
virtual int LexerInput (char *buf, int max_size)
virtual void LexerOutput (const char *buf, int size)
virtual void LexerError (const char *msg)
void yyunput (int c, char *buf_ptr)
int yyinput ()
void yy_load_buffer_state ()
void yy_init_buffer (struct yy_buffer_state *b, std::istream *s)
void yy_flush_buffer (struct yy_buffer_state *b)
void yy_push_state (int new_state)
void yy_pop_state ()
int yy_top_state ()
yy_state_type yy_get_previous_state ()
yy_state_type yy_try_NUL_trans (yy_state_type current_state)
int yy_get_next_buffer ()
void yyensure_buffer_stack (void)
Protected Attributes
int yy_start_stack_ptr
int yy_start_stack_depth
int * yy_start_stack
std::istream * yyin
std::ostream * yyout
char yy_hold_char
int yy_n_chars
char * yy_c_buf_p
int yy_init
int yy_start
int yy_did_buffer_switch_on_eof
size_t yy_buffer_stack_top
index of top of stack.
size_t yy_buffer_stack_max
capacity of stack.
struct yy_buffer_state ** yy_buffer_stack
Stack as an array.
yy_state_type yy_last_accepting_state
char * yy_last_accepting_cpos
yy_state_type * yy_state_buf
yy_state_type * yy_state_ptr
char * yy_full_match
int * yy_full_state
int yy_full_lp
int yy_lp
int yy_looking_for_trail_begin
int yy_more_flag
int yy_more_len
int yy_more_offset
int yy_prev_more_offset
Detailed Description
Definition at line 112 of file FlexLexer.h.
Constructor & Destructor Documentation
ExampleFlexLexer::ExampleFlexLexer (std::istream * arg_yyin = 0, std::ostream * arg_yyout = 0)
Definition at line 997 of file scanner.cc.
References yy_buffer_stack, yy_buffer_stack_max, yy_buffer_stack_top, yy_c_buf_p, yy_did_buffer_switch_on_eof, FlexLexer::yy_flex_debug, yy_init, yy_looking_for_trail_begin, yy_more_flag, yy_more_len, yy_more_offset, yy_prev_more_offset, yy_start, yy_start_stack, yy_start_stack_depth, yy_start_stack_ptr, yy_state_buf, yyin, FlexLexer::yylineno, and yyout.
ExampleFlexLexer::~ExampleFlexLexer () [virtual]
Definition at line 1027 of file scanner.cc.
References Examplefree(), yy_buffer_stack, YY_CURRENT_BUFFER, yy_delete_buffer(), yy_start_stack, and yy_state_buf.
Member Function Documentation
virtual void ExampleFlexLexer::LexerError (const char * msg) [protected, virtual]
int ExampleFlexLexer::LexerInput (char * buf, int max_size) [protected, virtual]
Definition at line 1052 of file scanner.cc.
void ExampleFlexLexer::LexerOutput (const char * buf, int size) [protected, virtual]
Definition at line 1079 of file scanner.cc.
References yyout.
void ExampleFlexLexer::switch_streams (std::istream * new_in, std::ostream * new_out) [virtual]
Implements FlexLexer.
Definition at line 1037 of file scanner.cc.
References YY_BUF_SIZE, yy_create_buffer(), YY_CURRENT_BUFFER, yy_delete_buffer(), yy_switch_to_buffer(), and yyout.
YY_BUFFER_STATE ExampleFlexLexer::yy_create_buffer (std::istream * file, int size) [read, virtual]
Allocate and initialize an input buffer state.
Parameters:
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
Returns:
the allocated buffer state.
Implements FlexLexer.
Definition at line 1502 of file scanner.cc.
References Examplealloc(), yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_init_buffer(), and yy_buffer_state::yy_is_our_buffer.
Referenced by switch_streams(), and yyrestart().
void ExampleFlexLexer::yy_delete_buffer (struct yy_buffer_state * b) [virtual]
Implements FlexLexer.
Referenced by switch_streams(), yypop_buffer_state(), and ~ExampleFlexLexer().
void ExampleFlexLexer::yy_flush_buffer (struct yy_buffer_state * b) [protected]
int ExampleFlexLexer::yy_get_next_buffer () [protected]
Definition at line 1097 of file scanner.cc.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, Examplerealloc(), yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yy_n_chars, YY_READ_BUF_SIZE, yyin, yyrestart(), and yytext_ptr.
Referenced by yyinput().
yy_state_type ExampleFlexLexer::yy_get_previous_state () [protected]
Definition at line 1237 of file scanner.cc.
References yy_accept, yy_base, yy_c_buf_p, yy_chk, yy_def, yy_ec, yy_last_accepting_cpos, yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yy_nxt, YY_SC_TO_UI, yy_start, and yytext_ptr.
void ExampleFlexLexer::yy_init_buffer (struct yy_buffer_state * b, std::istream * s) [protected]
Referenced by yy_create_buffer(), and yyrestart().
void ExampleFlexLexer::yy_load_buffer_state () [protected]
Definition at line 1484 of file scanner.cc.
References yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yy_hold_char, yy_n_chars, yyin, and yytext_ptr.
Referenced by yypop_buffer_state(), and yyrestart().
void ExampleFlexLexer::yy_pop_state () [protected]
Definition at line 1781 of file scanner.cc.
References BEGIN, YY_FATAL_ERROR, yy_start_stack, and yy_start_stack_ptr.
void ExampleFlexLexer::yy_push_state (int new_state) [protected]
Definition at line 1753 of file scanner.cc.
References BEGIN, Examplealloc(), Examplerealloc(), YY_FATAL_ERROR, YY_START, yy_start_stack, yy_start_stack_depth, YY_START_STACK_INCR, and yy_start_stack_ptr.
void ExampleFlexLexer::yy_switch_to_buffer (struct yy_buffer_state * new_buffer) [virtual]
Implements FlexLexer.
Referenced by switch_streams().
int ExampleFlexLexer::yy_top_state () [protected]
Definition at line 1793 of file scanner.cc.
References yy_start_stack, and yy_start_stack_ptr.
yy_state_type ExampleFlexLexer::yy_try_NUL_trans (yy_state_type current_state) [protected]
Definition at line 1275 of file scanner.cc.
References yy_accept, yy_base, yy_c_buf_p, yy_chk, yy_def, yy_last_accepting_cpos, yy_last_accepting_state, yy_meta, and yy_nxt.
void ExampleFlexLexer::yyensure_buffer_stack (void) [protected]
Definition at line 1696 of file scanner.cc.
References Examplealloc(), Examplerealloc(), yy_buffer_stack, yy_buffer_stack_max, yy_buffer_stack_top, and YY_FATAL_ERROR.
Referenced by yyrestart().
int ExampleFlexLexer::yyinput () [protected]
Definition at line 1348 of file scanner.cc.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yy_get_next_buffer(), yy_hold_char, yy_n_chars, YY_NEW_FILE, yyin, yyrestart(), yytext_ptr, and yywrap().
int ExampleFlexLexer::yylex () [virtual]
The main scanner function which does all the work.
Implements FlexLexer.
Definition at line 673 of file scanner.cc.
References example::Parser::token::DOUBLE, ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, example::Parser::token::EOL, INITIAL, example::Parser::token::INTEGER, example::Parser::token::STRING, yy_accept, yy_base, YY_BREAK, YY_BUF_SIZE, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yy_chk, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_def, YY_DO_BEFORE_ACTION, yy_ec, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_meta, YY_MORE_ADJ, YY_NEW_FILE, yy_nxt, YY_RESTORE_YY_MORE_OFFSET, yy_rule_linenum, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, YY_STATE_EOF, yyleng, yyterminate, and yytext_ptr.
void ExampleFlexLexer::yypop_buffer_state (void)
Removes and deletes the top of the stack, if present.
The next element becomes the new top.
Definition at line 1671 of file scanner.cc.
References yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_delete_buffer(), yy_did_buffer_switch_on_eof, and yy_load_buffer_state().
void ExampleFlexLexer::yypush_buffer_state (struct yy_buffer_state * new_buffer)
void ExampleFlexLexer::yyrestart (std::istream * input_file) [virtual]
Immediately switch to a different input stream.
Parameters:
input_file A readable stream.
Note:
This function does not reset the start condition to INITIAL .
Implements FlexLexer.
Definition at line 1428 of file scanner.cc.
References YY_BUF_SIZE, yy_create_buffer(), YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_buffer(), yy_load_buffer_state(), yyensure_buffer_stack(), and yyin.
Referenced by yy_get_next_buffer(), and yyinput().
void ExampleFlexLexer::yyunput (int c, char * buf_ptr) [protected]
int ExampleFlexLexer::yywrap () [virtual]
Definition at line 1948 of file scanner.cc.
Referenced by yyinput().
Member Data Documentation
struct yy_buffer_state** ExampleFlexLexer::yy_buffer_stack [read, protected]
Stack as an array.
Definition at line 184 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), yyensure_buffer_stack(), and ~ExampleFlexLexer().
size_t ExampleFlexLexer::yy_buffer_stack_max [protected]
capacity of stack.
Definition at line 183 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), and yyensure_buffer_stack().
size_t ExampleFlexLexer::yy_buffer_stack_top [protected]
index of top of stack.
Definition at line 182 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), yyensure_buffer_stack(), and yypop_buffer_state().
char* ExampleFlexLexer::yy_c_buf_p [protected]
Definition at line 172 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), yy_get_next_buffer(), yy_get_previous_state(), yy_load_buffer_state(), yy_try_NUL_trans(), and yyinput().
int ExampleFlexLexer::yy_did_buffer_switch_on_eof [protected]
Definition at line 179 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), yyinput(), and yypop_buffer_state().
int ExampleFlexLexer::yy_full_lp [protected]
Definition at line 198 of file FlexLexer.h.
char* ExampleFlexLexer::yy_full_match [protected]
Definition at line 196 of file FlexLexer.h.
int* ExampleFlexLexer::yy_full_state [protected]
Definition at line 197 of file FlexLexer.h.
char ExampleFlexLexer::yy_hold_char [protected]
Definition at line 166 of file FlexLexer.h.
Referenced by yy_load_buffer_state(), and yyinput().
int ExampleFlexLexer::yy_init [protected]
Definition at line 174 of file FlexLexer.h.
Referenced by ExampleFlexLexer().
char* ExampleFlexLexer::yy_last_accepting_cpos [protected]
Definition at line 191 of file FlexLexer.h.
Referenced by yy_get_previous_state(), and yy_try_NUL_trans().
yy_state_type ExampleFlexLexer::yy_last_accepting_state [protected]
Definition at line 190 of file FlexLexer.h.
Referenced by yy_get_previous_state(), and yy_try_NUL_trans().
int ExampleFlexLexer::yy_looking_for_trail_begin [protected]
Definition at line 201 of file FlexLexer.h.
Referenced by ExampleFlexLexer().
int ExampleFlexLexer::yy_lp [protected]
Definition at line 200 of file FlexLexer.h.
int ExampleFlexLexer::yy_more_flag [protected]
Definition at line 203 of file FlexLexer.h.
Referenced by ExampleFlexLexer().
int ExampleFlexLexer::yy_more_len [protected]
Definition at line 204 of file FlexLexer.h.
Referenced by ExampleFlexLexer().
int ExampleFlexLexer::yy_more_offset [protected]
Definition at line 205 of file FlexLexer.h.
Referenced by ExampleFlexLexer().
int ExampleFlexLexer::yy_n_chars [protected]
Definition at line 169 of file FlexLexer.h.
Referenced by yy_get_next_buffer(), yy_load_buffer_state(), and yyinput().
int ExampleFlexLexer::yy_prev_more_offset [protected]
Definition at line 206 of file FlexLexer.h.
Referenced by ExampleFlexLexer().
int ExampleFlexLexer::yy_start [protected]
Definition at line 175 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), and yy_get_previous_state().
int* ExampleFlexLexer::yy_start_stack [protected]
Definition at line 152 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), yy_pop_state(), yy_push_state(), yy_top_state(), and ~ExampleFlexLexer().
int ExampleFlexLexer::yy_start_stack_depth [protected]
Definition at line 151 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), and yy_push_state().
int ExampleFlexLexer::yy_start_stack_ptr [protected]
Definition at line 150 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), yy_pop_state(), yy_push_state(), and yy_top_state().
yy_state_type* ExampleFlexLexer::yy_state_buf [protected]
Definition at line 193 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), and ~ExampleFlexLexer().
yy_state_type* ExampleFlexLexer::yy_state_ptr [protected]
Definition at line 194 of file FlexLexer.h.
std:: istream* ExampleFlexLexer::yyin [protected]
Definition at line 162 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), yy_get_next_buffer(), yy_load_buffer_state(), yyinput(), and yyrestart().
std:: ostream* ExampleFlexLexer::yyout [protected]
Definition at line 163 of file FlexLexer.h.
Referenced by ExampleFlexLexer(), LexerOutput(), and switch_streams().
The documentation for this class was generated from the following files:
src/FlexLexer.h
src/scanner.cc